apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: seneschal
  namespace: seneschal
spec:
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: web
          port: 8080
